- id: manual_restart_homeassistant
  alias: "Manual Restart HomeAssistant"
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: input_button
        service: press
        service_data:
          entity_id: input_button.restart_homeassistant
  action:
    - service: homeassistant.restart

- id: manual_backup
  alias: "Manual Backup"
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: input_button
        service: press
        service_data:
          entity_id: input_button.manual_backup
  action:
    - service: shell_command.manual_backup
