# Commercial Greenhouse Configuration
homeassistant:
  name: Commercial Greenhouse
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Oslo
  country: "NO"

# HTTP with security
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.20.0.0/16
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Database – High-performance MariaDB
recorder:
  db_url: !secret db_url
  purge_keep_days: 365
  auto_purge: true
  commit_interval: 1
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - automation
      - fan
    entity_globs:
      - sensor.soil_*
      - sensor.tank_*
      - sensor.fan_*
      - sensor.battery_*
      - switch.solenoid_*
      - switch.*_valve

# MQTT (broker credentials now set via the UI integration)
mqtt:

# Notifications
notify:
  - name: critical_alerts
    platform: smtp
    server: !secret smtp_server
    port: 587
    sender: !secret smtp_sender
    username: !secret smtp_username
    password: !secret smtp_password
    recipient:
      - !secret admin_email

# Essential components
api:
logger:
  default: warning
  logs:
    homeassistant.components.recorder: info
system_health:
mobile_app:
frontend:
config:

automation: !include automations.yaml
script:     !include scripts.yaml
scene:      !include scenes.yaml

# --------  SENSORS  --------
sensor:
  # System-monitor sensors
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: load_1m

  - platform: uptime
    name: System Uptime

  # Template sensors
  - platform: template
    sensors:
      greenhouse_status:
        friendly_name: "Greenhouse Status"
        value_template: >
          {% set issues = [] %}
          {% if states('sensor.processor_use')  | int > 80 %} {% set issues = issues + ['High CPU'] %}{% endif %}
          {% if states('sensor.memory_use_percent') | int > 80 %} {% set issues = issues + ['High Memory'] %}{% endif %}
          {% if states('sensor.disk_use_percent') | int > 90 %} {% set issues = issues + ['Low Disk Space'] %}{% endif %}
          {% if is_state('binary_sensor.low_soil_moisture_alert', 'on') %} {% set issues = issues + ['Low Soil Moisture'] %}{% endif %}
          {{ 'Healthy' if issues | length == 0 else issues | join(', ') }}
        icon_template: >
          {% if is_state('binary_sensor.system_healthy','on')
                and is_state('binary_sensor.low_soil_moisture_alert','off') %}
            mdi:check-circle
          {% else %}
            mdi:alert-circle
          {% endif %}

      average_soil_moisture:
        friendly_name: "Average Soil Moisture"
        value_template: >
          {% set values = [
              states('sensor.soil_moisture_1') | float(0),
              states('sensor.soil_moisture_2') | float(0),
              states('sensor.soil_moisture_3') | float(0)
          ] | select('gt', 0) | list %}
          {{ (values | sum / values | length) | round(1)
               if values | length > 0 else 'unavailable' }}
        unit_of_measurement: "%"
        icon: mdi:water-percent

      average_soil_temperature:
        friendly_name: "Average Soil Temperature"
        value_template: >
          {% set temps = [
              states('sensor.soil_temperature_1') | float(-100),
              states('sensor.soil_temperature_2') | float(-100),
              states('sensor.soil_temperature_3') | float(-100)
          ] | select('gt', -50) | list %}
          {{ (temps | sum / temps | length) | round(1)
               if temps | length > 0 else 'unavailable' }}
        unit_of_measurement: "°C"
        icon: mdi:thermometer

# Binary sensors for system health
binary_sensor:
  - platform: template
    sensors:
      system_healthy:
        friendly_name: "System Health Status"
        value_template: >
          {{ states('sensor.processor_use')  | int < 80 and
             states('sensor.memory_use_percent') | int < 80 and
             states('sensor.disk_use_percent')   | int < 90 }}
        device_class: problem

      low_soil_moisture_alert:
        friendly_name: "Low Soil Moisture Alert"
        value_template: >
          {{ states('sensor.soil_moisture_1') | int < 25 or
             states('sensor.soil_moisture_2') | int < 25 or
             states('sensor.soil_moisture_3') | int < 25 }}
        device_class: problem

# Weather integration
weather:
  - platform: yr

# Input helpers
input_boolean:
  emergency_mode:
    name: Emergency Mode
    icon: mdi:alert-octagon
  irrigation_enabled:
    name: Irrigation System Enabled
    icon: mdi:water
  manual_irrigation_tomato:
    name: Manual Tomato Irrigation
    icon: mdi:water
  manual_irrigation_chili:
    name: Manual Chili Irrigation
    icon: mdi:water

input_number:
  target_soil_moisture:
    name: Target Soil Moisture
    min: 30
    max: 80
    step: 5
    unit_of_measurement: "%"
    icon: mdi:water-percent
  irrigation_duration:
    name: Irrigation Duration
    min: 5
    max: 30
    step: 1
    unit_of_measurement: "min"
    icon: mdi:timer

# Groups
group:
  soil_moisture_sensors:
    name: Soil Moisture Sensors
    entities:
      - sensor.soil_moisture_1
      - sensor.soil_moisture_2
      - sensor.soil_moisture_3

  soil_temperature_sensors:
    name: Soil Temperature Sensors
    entities:
      - sensor.soil_temperature_1
      - sensor.soil_temperature_2
      - sensor.soil_temperature_3

  tank_level_sensors:
    name: Tank Level Sensors
    entities:
      - sensor.main_tank_level
      - sensor.tank_a_calcinit_level
      - sensor.tank_b_nutrients_level
      - sensor.tank_c_mixed_level

  irrigation_controls:
    name: Irrigation Controls
    entities:
      - switch.solenoid_a_main_tank
      - switch.solenoid_b_tank_c
      - switch.tomato_zone_valve
      - switch.chili_zone_valve
      - switch.venturi_bypass_valve

# Zones
zone:
  - name: Greenhouse
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 100
    icon: mdi:greenhouse
