# Commercial Greenhouse Configuration
homeassistant:
  name: Commercial Greenhouse
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Oslo
  country: "NO"

# HTTP with security
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.20.0.0/16
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Database – High-performance MariaDB
recorder:
  db_url: !secret db_url
  purge_keep_days: 365
  auto_purge: true
  commit_interval: 1

# MQTT (broker credentials now set via the UI integration)
mqtt:
  sensor:
    # Device 1
    - name: "Greenhouse Climate 1 Temperature"
      state_topic: "greenhouse/climate1/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      
    - name: "Greenhouse Climate 1 Humidity"
      state_topic: "greenhouse/climate1/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      state_class: measurement
      
    - name: "Greenhouse Climate 1 WiFi Signal"
      state_topic: "greenhouse/climate1/wifi_signal"
      unit_of_measurement: "dBm"
      device_class: signal_strength
      entity_category: diagnostic
      
    # Device 2 (when you add it)
    - name: "Greenhouse Climate 2 Temperature"
      state_topic: "greenhouse/climate2/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      
    - name: "Greenhouse Climate 2 Humidity"
      state_topic: "greenhouse/climate2/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      state_class: measurement

    - name: "Greenhouse Climate 2 WiFi Signal"
      state_topic: "greenhouse/climate2/wifi_signal"
      unit_of_measurement: "dBm"
      device_class: signal_strength
      entity_category: diagnostic

  binary_sensor:
    - name: "Greenhouse Climate 1 Status"
      state_topic: "greenhouse/climate1/status"
      payload_on: "online"
      payload_off: "offline"
      device_class: connectivity
      
    - name: "Greenhouse Climate 2 Status"
      state_topic: "greenhouse/climate2/status"
      payload_on: "online"
      payload_off: "offline"
      device_class: connectivity

 switch:
    - name: "Greenhouse Climate 1 OTA Mode"
      state_topic: "greenhouse/climate1/ota_mode"
      command_topic: "greenhouse/climate1/ota_mode/set"
      payload_on: "ON"
      payload_off: "OFF"
      icon: mdi:upload-network

    - name: "Greenhouse Climate 2 OTA Mode"
      state_topic: "greenhouse/climate2/ota_mode"
      command_topic: "greenhouse/climate2/ota_mode/set"
      payload_on: "ON"
      payload_off: "OFF"
      icon: mdi:upload-network


# Notifications
notify:
  - platform: smtp
    name: critical_alerts
    server: !secret smtp_server
    port: 587
    sender: !secret smtp_sender
    username: !secret smtp_username
    password: !secret smtp_password
    recipient:
      - !secret admin_email

# Essential components
api:
logger:
  default: warning
  logs:
    homeassistant.components.recorder: info
system_health:
mobile_app:
frontend:
config:

automation: !include automations.yaml
script:     !include scripts.yaml
scene:      !include scenes.yaml

# Zones
zone:
  - name: Greenhouse
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 100
    icon: mdi:greenhouse
