# Commercial Greenhouse Configuration
homeassistant:
  name: Commercial Greenhouse
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Oslo
  country: "NO"

# HTTP with security
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.20.0.0/16
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Database – High-performance MariaDB
recorder:
  db_url: !secret db_url
  purge_keep_days: 365
  auto_purge: true
  commit_interval: 1
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - automation
      - fan
    entity_globs:
      - sensor.soil_*
      - sensor.tank_*
      - sensor.fan_*
      - sensor.battery_*
      - switch.solenoid_*
      - switch.*_valve

# MQTT (broker credentials now set via the UI integration)
mqtt:

# Notifications
notify:
  - name: critical_alerts
    platform: smtp
    server: !secret smtp_server
    port: 587
    sender: !secret smtp_sender
    username: !secret smtp_username
    password: !secret smtp_password
    recipient:
      - !secret admin_email

# Essential components
api:
logger:
  default: warning
  logs:
    homeassistant.components.recorder: info
system_health:
mobile_app:
frontend:
config:

automation: !include automations.yaml
script:     !include scripts.yaml
scene:      !include scenes.yaml

# Zones
zone:
  - name: Greenhouse
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 100
    icon: mdi:greenhouse
