# Scripts for Greenhouse Control System

gh_notify:
  alias: "GH Notify"
  mode: parallel
  fields:
    title: {description: "Title"}
    message: {description: "Message"}
  sequence:
    - service: persistent_notification.create
      data:
        title: "{{ title }}"
        message: "{{ message }}"
    - service: notify.mobile_app_kim_aleksander_hammer_sin_iphone
      continue_on_error: true
      data:
        title: "{{ title }}"
        message: "{{ message }}"
