# Scripts for Greenhouse Control System

gh_notify:
  alias: "GH Notify"
  mode: parallel
  fields:
    title: {description: "Title"}
    message: {description: "Message"}
  sequence:
    - service: persistent_notification.create
      data:
        title: "{{ title }}"
        message: "{{ message }}"
